const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC_RI = path.join(ROOT, 'ri');
const DIST = path.join(ROOT, 'dist');
const DIST_RI = path.join(DIST, 'ri');
const CONFIG_FILE = path.join(ROOT, 'config.json');

// Helper: Shuffle Array (Fisher-Yates)
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Load configuration
function loadConfig() {
    let config = { domain: '' };

    if (process.env.DOMAIN) {
        config.domain = process.env.DOMAIN;
        console.log('Loaded domain from environment variable.');
    } else if (fs.existsSync(CONFIG_FILE)) {
        try {
            const configContent = fs.readFileSync(CONFIG_FILE, 'utf8');
            const parsed = JSON.parse(configContent);
            if (parsed.domain) {
                config.domain = parsed.domain;
            }
            console.log('Loaded domain from config.json.');
        } catch (e) {
            console.warn('Failed to parse config.json, using default settings.');
        }
    }

    if (config.domain) {
        config.domain = config.domain.replace(/\/$/, '');
    }

    console.log(`Using domain prefix: "${config.domain}"`);
    return config;
}

// Process images from ri/h and ri/v
function processImages() {
    const types = ['h', 'v'];
    const counts = {};

    types.forEach(type => {
        const srcFolder = path.join(SRC_RI, type);
        const distFolder = path.join(DIST_RI, type);

        if (!fs.existsSync(srcFolder)) {
            console.warn(`Source folder not found: ${srcFolder}`);
            counts[type] = 0;
            return;
        }

        fs.mkdirSync(distFolder, { recursive: true });

        let files = fs.readdirSync(srcFolder).filter(f => f.match(/\.(webp|jpg|jpeg|png|gif)$/i));
        files = shuffle(files);

        files.forEach((file, index) => {
            const srcPath = path.join(srcFolder, file);
            const destPath = path.join(distFolder, `${index + 1}.webp`);
            fs.copyFileSync(srcPath, destPath);
        });

        counts[type] = files.length;
        console.log(`Processed ${type}: ${counts[type]} images.`);
    });

    return counts;
}

// Generate serverless function for /random/{type}
function makeRandomFn(type, counts) {
    return `/**
 * Random image endpoint /random/${type}
 * Generated by build.js
 */
const COUNTS = ${JSON.stringify(counts)};

function jsonResponse(body, status, extraHeaders = {}) {
    return new Response(JSON.stringify(body, null, 2), {
        status,
        headers: {
            'content-type': 'application/json; charset=utf-8',
            ...extraHeaders
        }
    });
}

function corsHeaders() {
    return {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Max-Age': '86400',
        'Vary': 'Origin'
    };
}

export async function onRequest(context) {
    try {
        const request = context.request;
        const cors = corsHeaders();

        if (request.method === 'OPTIONS') {
            return new Response(null, { status: 204, headers: cors });
        }

        const total = COUNTS['${type}'];

        if (!total || total < 1) {
            return jsonResponse({ error: 'No images for type ${type}' }, 404, cors);
        }

        const idx = Math.floor(Math.random() * total) + 1;
        const host = (request && request.headers && request.headers.get('host')) || 'pic.olinl.com';
        const proto = (request && request.headers && request.headers.get('x-forwarded-proto')) || 'https';
        const target = proto + '://' + host + '/ri/${type}/' + idx + '.webp';

        return new Response(null, {
            status: 302,
            headers: {
                ...cors,
                'location': target,
                'cache-control': 'no-cache, no-store, must-revalidate, max-age=0'
            }
        });
    } catch (e) {
        return jsonResponse({
            error: 'function crashed',
            message: e && e.message,
            stack: e && e.stack
        }, 500);
    }
}
`;
}

// Generate serverless function for /random/ua
function makeUaFn(counts) {
    return `/**
 * User-Agent adaptive random image endpoint /random/ua
 * Generated by build.js
 */
const COUNTS = ${JSON.stringify(counts)};

function jsonResponse(body, status, extraHeaders = {}) {
    return new Response(JSON.stringify(body, null, 2), {
        status,
        headers: {
            'content-type': 'application/json; charset=utf-8',
            ...extraHeaders
        }
    });
}

function corsHeaders() {
    return {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Max-Age': '86400',
        'Vary': 'Origin, User-Agent'
    };
}

export async function onRequest(context) {
    try {
        const request = context.request;
        const cors = corsHeaders();

        if (request.method === 'OPTIONS') {
            return new Response(null, { status: 204, headers: cors });
        }

        const userAgent = ((request && request.headers && request.headers.get('user-agent')) || '').toLowerCase();
        const isMobile = /android|ipad|iphone|ipod|windows phone|iemobile|blackberry|mobile/i.test(userAgent);
        const type = isMobile ? 'v' : 'h';
        const total = COUNTS[type];

        if (!total || total < 1) {
            return jsonResponse({ error: 'No images for type ' + type }, 404, cors);
        }

        const idx = Math.floor(Math.random() * total) + 1;
        const host = (request && request.headers && request.headers.get('host')) || 'pic.olinl.com';
        const proto = (request && request.headers && request.headers.get('x-forwarded-proto')) || 'https';
        const target = proto + '://' + host + '/ri/' + type + '/' + idx + '.webp';

        return new Response(null, {
            status: 302,
            headers: {
                ...cors,
                'location': target,
                'cache-control': 'no-cache, no-store, must-revalidate, max-age=0'
            }
        });
    } catch (e) {
        return jsonResponse({
            error: 'function crashed',
            message: e && e.message,
            stack: e && e.stack
        }, 500);
    }
}
`;
}

// Write serverless functions to both functions/ and edge-functions/
function writeServerlessFunctions(counts) {
    function writeFn(folder, subPath, filename, content) {
        const dir = path.join(ROOT, folder, subPath);
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, filename), content);

        const dstDir = path.join(DIST, folder, subPath);
        fs.mkdirSync(dstDir, { recursive: true });
        fs.writeFileSync(path.join(dstDir, filename), content);
    }

    for (const folder of ['functions', 'edge-functions']) {
        writeFn(folder, 'random', 'h.js', makeRandomFn('h', counts));
        writeFn(folder, 'random', 'v.js', makeRandomFn('v', counts));
        writeFn(folder, 'random', 'ua.js', makeUaFn(counts));
        console.log(`Wrote ${folder}/random/{h,v,ua}.js`);
    }

    // Clean up legacy /api/status and [type].js files
    for (const folder of ['functions', 'edge-functions']) {
        const legacyType = path.join(ROOT, folder, 'random', '[type].js');
        if (fs.existsSync(legacyType)) {
            fs.unlinkSync(legacyType);
            console.log(`Removed legacy ${folder}/random/[type].js`);
        }
        const legacyTypeDist = path.join(DIST, folder, 'random', '[type].js');
        if (fs.existsSync(legacyTypeDist)) {
            fs.unlinkSync(legacyTypeDist);
            console.log(`Removed legacy dist/${folder}/random/[type].js`);
        }

        const statusDir = path.join(ROOT, folder, 'api', 'status');
        if (fs.existsSync(statusDir)) {
            fs.rmSync(statusDir, { recursive: true, force: true });
            console.log(`Removed legacy ${folder}/api/status`);
        }
        const statusDirDist = path.join(DIST, folder, 'api', 'status');
        if (fs.existsSync(statusDirDist)) {
            fs.rmSync(statusDirDist, { recursive: true, force: true });
            console.log(`Removed legacy dist/${folder}/api/status`);
        }
    }
}

// Generate API documentation index.html
function createApiHtml(counts, config) {
    const domain = config.domain || '';
    const baseUrl = domain || 'https://your-domain.com';
    const uaUrl = `${baseUrl}/random/ua`;
    const hUrl = `${baseUrl}/random/h`;
    const vUrl = `${baseUrl}/random/v`;

    const htmlContent = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pic API - Static Random Image API</title>
    <style>
        :root {
            --bg: #0f0f12;
            --surface: #18181c;
            --surface-light: #222228;
            --text: #f0f0f5;
            --text-muted: #9ca3af;
            --accent: #3b82f6;
            --accent-hover: #2563eb;
            --border: #2a2a30;
        }
        * { box-sizing: border-box; }
        body {
            margin: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 60px 20px;
        }
        header { text-align: center; margin-bottom: 50px; }
        h1 {
            font-size: 3rem;
            margin: 0 0 12px;
            background: linear-gradient(135deg, #60a5fa, #a78bfa);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
        .subtitle { color: var(--text-muted); font-size: 1.1rem; }
        .stats {
            display: flex;
            justify-content: center;
            gap: 40px;
            margin: 40px 0;
            flex-wrap: wrap;
        }
        .stat {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 16px;
            padding: 24px 40px;
            text-align: center;
            min-width: 140px;
        }
        .stat-value {
            font-size: 2.5rem;
            font-weight: 700;
            color: var(--accent);
        }
        .stat-label { color: var(--text-muted); font-size: 0.9rem; margin-top: 4px; }
        .endpoint {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 16px;
            padding: 24px;
            margin-bottom: 20px;
        }
        .endpoint-header {
            display: flex;
            align-items: center;
            gap: 12px;
            margin-bottom: 10px;
            flex-wrap: wrap;
        }
        .method {
            background: var(--accent);
            color: white;
            padding: 4px 10px;
            border-radius: 6px;
            font-size: 0.75rem;
            font-weight: 700;
        }
        .path {
            font-family: "SF Mono", Monaco, monospace;
            font-size: 1rem;
            color: var(--text);
        }
        .desc { color: var(--text-muted); margin: 0 0 14px; }
        code {
            background: #0b0b0e;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: "SF Mono", Monaco, monospace;
            color: #60a5fa;
        }
        .code-block {
            position: relative;
            margin: 0 0 14px;
        }
        pre {
            background: #0b0b0e;
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 14px 70px 14px 14px;
            overflow-x: auto;
            margin: 0;
        }
        pre code {
            background: transparent;
            padding: 0;
            color: #e2e8f0;
        }
        .copy-btn {
            position: absolute;
            top: 8px;
            right: 8px;
            background: var(--surface-light);
            border: 1px solid var(--border);
            color: var(--text-muted);
            padding: 4px 10px;
            border-radius: 6px;
            cursor: pointer;
            font-size: 0.8rem;
            transition: all 0.2s;
        }
        .copy-btn:hover {
            border-color: var(--accent);
            color: var(--text);
        }
        .copy-btn.copied {
            background: var(--accent);
            color: white;
            border-color: var(--accent);
        }
        .preview {
            margin-top: 14px;
            padding-top: 14px;
            border-top: 1px solid var(--border);
        }
        .preview-label {
            color: var(--text-muted);
            font-size: 0.85rem;
            margin-bottom: 10px;
        }
        .preview img {
            max-width: 100%;
            max-height: 260px;
            border-radius: 10px;
            background: var(--surface-light);
            display: block;
        }
        .btn {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            background: var(--accent);
            color: white;
            padding: 10px 20px;
            border-radius: 8px;
            text-decoration: none;
            font-weight: 500;
            transition: background 0.2s;
        }
        .btn:hover { background: var(--accent-hover); }
        .links { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 16px; }
        footer {
            text-align: center;
            color: var(--text-muted);
            margin-top: 60px;
            font-size: 0.9rem;
        }
        @media (max-width: 600px) {
            h1 { font-size: 2rem; }
            .stat { padding: 18px 28px; }
            .endpoint { padding: 18px; }
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Pic API</h1>
            <p class="subtitle">一个纯粹的静态随机图 API</p>
            <div class="stats">
                <div class="stat">
                    <div class="stat-value">${counts.h || 0}</div>
                    <div class="stat-label">横屏图片</div>
                </div>
                <div class="stat">
                    <div class="stat-value">${counts.v || 0}</div>
                    <div class="stat-label">竖屏图片</div>
                </div>
            </div>
        </header>

        <div class="endpoint">
            <div class="endpoint-header">
                <span class="method">GET</span>
                <span class="path">/random/ua</span>
            </div>
            <p class="desc">根据 User-Agent 自动适配：PC 返回横屏，移动端返回竖屏。</p>
            <div class="code-block">
                <pre><code>${uaUrl}</code></pre>
                <button class="copy-btn" data-copy="${uaUrl}">复制</button>
            </div>
            <div class="preview">
                <div class="preview-label">预览</div>
                <img src="${uaUrl}" alt="ua random" loading="lazy">
            </div>
        </div>

        <div class="endpoint">
            <div class="endpoint-header">
                <span class="method">GET</span>
                <span class="path">/random/h</span>
            </div>
            <p class="desc">随机返回一张横屏图片。</p>
            <div class="code-block">
                <pre><code>${hUrl}</code></pre>
                <button class="copy-btn" data-copy="${hUrl}">复制</button>
            </div>
            <div class="preview">
                <div class="preview-label">预览</div>
                <img src="${hUrl}" alt="horizontal random" loading="lazy">
            </div>
        </div>

        <div class="endpoint">
            <div class="endpoint-header">
                <span class="method">GET</span>
                <span class="path">/random/v</span>
            </div>
            <p class="desc">随机返回一张竖屏图片。</p>
            <div class="code-block">
                <pre><code>${vUrl}</code></pre>
                <button class="copy-btn" data-copy="${vUrl}">复制</button>
            </div>
            <div class="preview">
                <div class="preview-label">预览</div>
                <img src="${vUrl}" alt="vertical random" loading="lazy">
            </div>
        </div>

        <div class="links">
            <a class="btn" href="/random/ua" target="_blank">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 3h5v5"/><path d="M4 20L21 3"/><path d="M21 16v5h-5"/><path d="M15 15l6 6"/><path d="M4 4l5 5"/></svg>
                随机来一张
            </a>
            <a class="btn" href="/gallery.html" style="background: var(--surface); border: 1px solid var(--border);">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg>
                浏览画廊
            </a>
        </div>

    </div>

    <script>
        document.querySelectorAll('.copy-btn').forEach(btn => {
            btn.addEventListener('click', async () => {
                const text = btn.dataset.copy;
                try {
                    await navigator.clipboard.writeText(text);
                    const original = btn.textContent;
                    btn.textContent = '已复制';
                    btn.classList.add('copied');
                    setTimeout(() => {
                        btn.textContent = original;
                        btn.classList.remove('copied');
                    }, 1500);
                } catch (e) {
                    btn.textContent = '失败';
                    setTimeout(() => btn.textContent = '复制', 1500);
                }
            });
        });
    </script>
</body>
</html>`;

    fs.writeFileSync(path.join(DIST, 'index.html'), htmlContent);
    console.log('Created API documentation index.html in dist');
}

// Generate gallery page with in-page filtering
function createGalleryHtml(counts, config) {
    const domain = config.domain || '';
    const types = ['h', 'v'].filter(t => counts[t] > 0);

    let navButtons = `<button class="filter-btn active" data-filter="all">All</button>`;
    let galleryContent = '';

    types.forEach(type => {
        const count = counts[type];
        navButtons += `<button class="filter-btn" data-filter="${type}">${type.toUpperCase()} (${count})</button>`;

        let itemsHtml = '';
        for (let i = 1; i <= count; i++) {
            const url = domain ? `${domain}/ri/${type}/${i}.webp` : `./ri/${type}/${i}.webp`;
            itemsHtml += `
                <div class="grid-item" data-type="${type}">
                    <div class="skeleton"></div>
                    <img class="lazy-img" data-src="${url}" data-full="${url}" alt="${type}-${i}" loading="lazy">
                </div>
            `;
        }

        galleryContent += `
            <section id="section-${type}" class="gallery-section">
                <h2>${type.toUpperCase()} <span>${count}</span></h2>
                <div class="masonry">
                    ${itemsHtml}
                </div>
            </section>
        `;
    });

    const htmlContent = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gallery - Pic API</title>
    <style>
        :root {
            --bg: #0a0a0c;
            --surface: #141417;
            --surface-light: #1f1f24;
            --text: #f1f1f6;
            --text-muted: #9ca3af;
            --accent: #3b82f6;
            --accent-hover: #2563eb;
            --border: #27272e;
        }
        * { box-sizing: border-box; }
        body {
            margin: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background: var(--bg);
            color: var(--text);
            padding-bottom: 60px;
        }
        header {
            position: sticky;
            top: 0;
            z-index: 100;
            background: rgba(10, 10, 12, 0.85);
            backdrop-filter: blur(16px);
            border-bottom: 1px solid var(--border);
            padding: 20px;
        }
        .header-inner {
            max-width: 1600px;
            margin: 0 auto;
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 16px;
        }
        h1 {
            margin: 0;
            font-size: 1.6rem;
        }
        h1 a {
            background: linear-gradient(135deg, #60a5fa, #a78bfa);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            text-decoration: none;
        }
        .filter-nav {
            display: flex;
            gap: 10px;
            flex-wrap: wrap;
        }
        .filter-btn {
            background: var(--surface);
            border: 1px solid var(--border);
            color: var(--text-muted);
            padding: 8px 18px;
            border-radius: 999px;
            cursor: pointer;
            font-size: 0.9rem;
            transition: all 0.2s;
        }
        .filter-btn:hover {
            border-color: var(--accent);
            color: var(--text);
        }
        .filter-btn.active {
            background: var(--accent);
            border-color: var(--accent);
            color: white;
        }
        .back-link {
            color: var(--text-muted);
            text-decoration: none;
            font-size: 0.9rem;
            transition: color 0.2s;
        }
        .back-link:hover { color: var(--text); }
        .container {
            max-width: 1600px;
            margin: 0 auto;
            padding: 30px 20px;
        }
        .gallery-section h2 {
            font-size: 1.1rem;
            color: var(--text-muted);
            margin: 30px 0 16px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .gallery-section h2 span {
            color: var(--text);
            margin-left: 8px;
            font-size: 0.9rem;
        }
        .masonry {
            column-count: 5;
            column-gap: 16px;
        }
        .grid-item {
            break-inside: avoid;
            margin-bottom: 16px;
            position: relative;
            border-radius: 12px;
            overflow: hidden;
            background: var(--surface);
            cursor: zoom-in;
            transition: transform 0.3s, box-shadow 0.3s;
        }
        .grid-item:hover {
            transform: translateY(-4px);
            box-shadow: 0 12px 30px rgba(0,0,0,0.5);
        }
        .grid-item.hidden { display: none; }
        .skeleton {
            position: absolute;
            inset: 0;
            background: linear-gradient(90deg, var(--surface) 25%, var(--surface-light) 50%, var(--surface) 75%);
            background-size: 200% 100%;
            animation: shimmer 1.5s infinite;
            z-index: 1;
        }
        @keyframes shimmer {
            0% { background-position: 200% 0; }
            100% { background-position: -200% 0; }
        }
        .lazy-img {
            display: block;
            width: 100%;
            height: auto;
            opacity: 0;
            transition: opacity 0.5s ease;
            position: relative;
            z-index: 2;
        }
        .lazy-img.loaded { opacity: 1; }

        /* Lightbox */
        .lightbox {
            position: fixed;
            inset: 0;
            background: rgba(0,0,0,0.92);
            display: none;
            align-items: center;
            justify-content: center;
            z-index: 1000;
            padding: 20px;
            opacity: 0;
            transition: opacity 0.3s;
        }
        .lightbox.active { display: flex; opacity: 1; }
        .lightbox img {
            max-width: 100%;
            max-height: 90vh;
            border-radius: 8px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.8);
        }
        .lightbox-close {
            position: absolute;
            top: 20px;
            right: 30px;
            font-size: 2.5rem;
            color: white;
            cursor: pointer;
            opacity: 0.7;
            transition: opacity 0.2s;
        }
        .lightbox-close:hover { opacity: 1; }

        @media (max-width: 1400px) { .masonry { column-count: 4; } }
        @media (max-width: 1100px) { .masonry { column-count: 3; } }
        @media (max-width: 768px) { .masonry { column-count: 2; column-gap: 12px; } .grid-item { margin-bottom: 12px; } }
        @media (max-width: 480px) { .masonry { column-count: 1; } }
    </style>
</head>
<body>
    <header>
        <div class="header-inner">
            <h1><a href="/">Gallery</a></h1>
            <nav class="filter-nav">
                ${navButtons}
            </nav>
        </div>
    </header>

    <main class="container">
        ${galleryContent}
    </main>

    <div class="lightbox" id="lightbox">
        <span class="lightbox-close">&times;</span>
        <img src="" alt="full" id="lightbox-img">
    </div>

    <script>
        // Lazy loading with IntersectionObserver
        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    const img = entry.target;
                    const src = img.dataset.src;
                    if (!src) return;

                    const temp = new Image();
                    temp.src = src;
                    temp.onload = () => {
                        img.src = src;
                        img.classList.add('loaded');
                        const skeleton = img.parentElement.querySelector('.skeleton');
                        if (skeleton) skeleton.style.display = 'none';
                    };
                    temp.onerror = () => {
                        img.style.opacity = '0.3';
                    };
                    observer.unobserve(img);
                }
            });
        }, {
            rootMargin: '200px 0px'
        });

        document.querySelectorAll('.lazy-img').forEach(img => observer.observe(img));

        // Filter buttons
        document.querySelectorAll('.filter-btn').forEach(btn => {
            btn.addEventListener('click', () => {
                document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
                btn.classList.add('active');
                const filter = btn.dataset.filter;

                document.querySelectorAll('.grid-item').forEach(item => {
                    if (filter === 'all' || item.dataset.type === filter) {
                        item.classList.remove('hidden');
                    } else {
                        item.classList.add('hidden');
                    }
                });

                document.querySelectorAll('.gallery-section').forEach(sec => {
                    if (filter === 'all' || sec.id === 'section-' + filter) {
                        sec.style.display = 'block';
                    } else {
                        sec.style.display = 'none';
                    }
                });
            });
        });

        // Lightbox
        const lightbox = document.getElementById('lightbox');
        const lightboxImg = document.getElementById('lightbox-img');

        document.querySelectorAll('.grid-item').forEach(item => {
            item.addEventListener('click', () => {
                const img = item.querySelector('.lazy-img');
                if (img && img.dataset.full) {
                    lightboxImg.src = img.dataset.full;
                    lightbox.classList.add('active');
                }
            });
        });

        lightbox.addEventListener('click', (e) => {
            if (e.target !== lightboxImg) {
                lightbox.classList.remove('active');
                lightboxImg.src = '';
            }
        });

        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape') {
                lightbox.classList.remove('active');
                lightboxImg.src = '';
            }
        });
    </script>
</body>
</html>`;

    fs.writeFileSync(path.join(DIST, 'gallery.html'), htmlContent);
    console.log('Created gallery.html in dist');
}

// Main build function
function build() {
    console.log('Starting build...');

    const config = loadConfig();

    // Clean/Create Dist
    if (fs.existsSync(DIST)) {
        try {
            fs.rmSync(DIST, { recursive: true, force: true });
        } catch (e) {
            // If dist directory is locked (e.g. by a running local server),
            // clean its contents instead of removing the directory itself.
            console.warn('Could not remove dist directory, cleaning contents instead...');
            fs.readdirSync(DIST).forEach(entry => {
                const entryPath = path.join(DIST, entry);
                fs.rmSync(entryPath, { recursive: true, force: true });
            });
        }
    }
    fs.mkdirSync(DIST, { recursive: true });
    fs.mkdirSync(DIST_RI, { recursive: true });

    // Process images
    const counts = processImages();

    // Write counts.json
    fs.writeFileSync(
        path.join(DIST, 'counts.json'),
        JSON.stringify(counts, null, 2)
    );
    console.log(`Wrote dist/counts.json: ${JSON.stringify(counts)}`);

    // Write serverless functions
    writeServerlessFunctions(counts);

    // Generate pages
    createApiHtml(counts, config);
    createGalleryHtml(counts, config);

    console.log('Build complete. Output is in /dist folder.');
}

build();
