/**
 * Random image endpoint /random/v
 * Generated by build.js
 */
const COUNTS = {"h":979,"v":3596};

function jsonResponse(body, status, extraHeaders = {}) {
    return new Response(JSON.stringify(body, null, 2), {
        status,
        headers: {
            'content-type': 'application/json; charset=utf-8',
            ...extraHeaders
        }
    });
}

function corsHeaders() {
    return {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Max-Age': '86400',
        'Vary': 'Origin'
    };
}

export async function onRequest(context) {
    try {
        const request = context.request;
        const cors = corsHeaders();

        if (request.method === 'OPTIONS') {
            return new Response(null, { status: 204, headers: cors });
        }

        const total = COUNTS['v'];

        if (!total || total < 1) {
            return jsonResponse({ error: 'No images for type v' }, 404, cors);
        }

        const idx = Math.floor(Math.random() * total) + 1;
        const host = (request && request.headers && request.headers.get('host')) || 'pic.u1u.top';
        const proto = (request && request.headers && request.headers.get('x-forwarded-proto')) || 'https';
        const target = proto + '://' + host + '/ri/v/' + idx + '.webp';

        return new Response(null, {
            status: 302,
            headers: {
                ...cors,
                'location': target,
                'cache-control': 'no-cache, no-store, must-revalidate, max-age=0'
            }
        });
    } catch (e) {
        return jsonResponse({
            error: 'function crashed',
            message: e && e.message,
            stack: e && e.stack
        }, 500);
    }
}
